version: "3"
services:
  olgareklamanaavto:
    image: valeriyshashkin/olgareklamanaavto:latest
    ports:
      - "3000"
    networks:
      - app-network
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
networks:
  app-network:
    driver: bridge